Correspondance tables
Team-Arduino-Logique/Arduino-Logique pull request #71
Opened 2024-11-12 17:29 UTC by abbou169

ajout de tables de correspondances de PIN avec les IO des microcontrolleurs:

1) placer les entrées et sorties dans la board
2) aller dans le menu controllers et selectionner un microcontrolleur
3) aller dans le menu export (qui va contronir le bouton de téléversement après) et appuier sur show correspondance

pour l'instant j'ai mis les numero des pin au dessus des objets pin_io mais il faudra trouver un meilleur layout pour que ce soit plus visible, j'ai créé un issue pour ça.

2024-11-12 18:00 UTC, charlotrudel commented
Le label dans le tableau _io_pin_X n'est pas nécessairement clair par rapport aux IOs sur le board. Les numéros ne sont pas non plus super visibles sur les IOs sur le board. Est-ce qu'on peut afficher ça de manière un peu plus claire?

2024-11-12 20:29 UTC, charlotrudel commented
Aussi, est-ce que la sélection de microcontrôleur peut être dans un menu plus clair et/ou écrit en quelque part?

2024-11-12 20:31 UTC, abbou169 commented
J'ai créé un issue pour l'affichage des IO sur les boards. Je voulais en discuter en réunion cette semaine. Mais si t'a le temps ce soir on peut discuter de ça et de la sélection des microcontrôleurs.   
Pour les _io_pin_X dans le tableau, je vais corriger ça live.

2024-11-12 20:41 UTC, charlotrudel approved these changes

2024-11-12 21:17 UTC, charlotrudel requested changes
![image](https://github.com/user-attachments/assets/f32fb7d8-a5f3-43cb-86d6-3ad7519b1460)

2024-11-13 02:31 UTC, charlotrudel approved these changes

2024-11-13 02:31 UTC, merged